version: '3'

services:
  setup:
    image: elswork/apache2-utils
    volumes:
      - .:/data
    command: htpasswd -cb /data/htpasswd pypiuser 123456

  osssync:
    image: registry.cn-zhangjiakou.aliyuncs.com/baiyigali/osssync:v0.0.0.6
    container_name: osssync
    volumes:
      - /home/baiyigali/workspace/pypiserver/packages:/app/data
    environment:
      - OSS_ENDPOINT=<<OSS_ENDPOINT>>
      - OSS_ACCESS_KEY_ID=<<OSS_ACCESS_KEY_ID>>
      - OSS_ACCESS_KEY_SECRET=<<OSS_ACCESS_KEY_SECRET>>
      - OSS_BUCKET_NAME=<<OSS_BUCKET_NAME>>
      - OSS_DIR=
      - LOCAL_DIR=/app/data
    restart: unless-stopped

  pypi:
    image: pypiserver/pypiserver:v1.5.1
    container_name: pypiserver
    depends_on:
      - setup
      - osssync
    ports:
      - "4500:8080"
    volumes:
      - ./packages:/data/packages
      - ./htpasswd:/data/.htpasswd
    environment:
      - PYPISERVER_PASSWORDS_FILE=/data/.htpasswd
    restart: always
    command: run -P /data/.htpasswd -a download,update,list /data/packages
