version: '3'

services:
  setup:
    image: elswork/apache2-utils
    volumes:
      - ./htpasswd:/etc/nginx/htpasswd
    command: htpasswd -cb /etc/nginx/htpasswd pypiuser 123456
  pypi:
    image: pypiserver/pypiserver:v1.5.1
    depends_on:
      - setup
    ports:
      - "4599:8080"
    volumes:
      - ./packages:/data/packages
      - ./htpasswd:/data/.htpasswd:ro
    environment:
      - PYPISERVER_PASSWORDS_FILE=/data/.htpasswd
    restart: always
    command: run -P /data/.htpasswd -a download,update,list /data/packages
