name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: ["main", "master" ]

env:
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  DEPLOY_FOLDER: "/home/baiyigali/workspace/pypiserver"
  OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
  OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
  OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
  OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
jobs:
  deploy_int:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}

    steps:
    - uses: actions/checkout@v3

    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '<<'
        tokenSuffix: '>>'
        files: '["docker-compose.yml"]'

    - name: Bash - Show docker-compose.yml
      run: cat docker-compose.yml

    - name: SCP file
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.SERVER_IP }}
        username: ${{ env.SERVER_USERNAME }}
        password: ${{ env.SERVER_PASSWORD }}        
        port: 22
        source: "docker-compose.yml"
        target: ${{ env.DEPLOY_FOLDER }}
        overwrite: true
  
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_IP }}
        username: ${{ env.SERVER_USERNAME }}
        password: ${{ env.SERVER_PASSWORD }}
        script: |
          cd /home/baiyigali/workspace/pypiserver
          docker compose pull
          docker compose up -d
